export { Calendar } from './Calendar/Calendar'
export { Staff } from './Staff/Staff'
export { Home } from './Home/Home'
export { Pharmacist } from './Pharmacist/Pharmacist'
export { Manage } from './Manage/Manage'